# -*- coding: utf-8 -*-
source 'https://rubygems.org'


# rails
gem 'rails', '~> 4.2.7.1'
gem 'autoprefixer-rails', '~> 6.3.6.1'

#db
gem 'pg'
gem 'postgres_ext', '~> 3.0.0'

gem 'doorkeeper', '~> 3.1.0'
gem 'rack-attack', '~> 4.4.1' # api limit
gem 'rack-cors', '~> 0.4.0'

# Use Puma as the app server
gem 'puma', '~> 3.4.0'
gem 'jbuilder', '~> 2.4.1'

gem 'oneapm_rpm', '~> 1.3.6'
gem 'httparty', '~> 0.13.7'

gem 'multi_fetch_fragments'
gem 'unscoped_associations' # support unscoped for association

gem 'factory_girl_rails', '~> 4.7.0'
gem 'ffaker'
gem 'byebug'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'parser', '2.3.1.0'

gem 'aasm', '~> 4.10'
gem 'bcrypt', '~> 3.1.11'
gem 'cancancan', '~> 1.14.0'
gem 'paranoia', '~> 2.1.5' # 软删除

gem 'acts_as_list'
gem 'ruby-pinyin', '~> 0.5.0'
gem 'mini_magick', '~> 4.5.1'
gem 'has_scope', '~> 0.7.0'
gem 'paper_trail', '~> 5.0.1'
gem 'json-schema', '~> 2.6.2'
gem 'kaminari', '~> 0.16.3'
gem 'letter_avatar'

gem 'redis', '~> 3.3.0'
gem 'redis-rails', '~> 4.0.0'

gem 'redis-namespace' # removed from sidekiq dependence, we still need it
gem 'wisper', '~> 2.0.0.rc1'
gem 'wisper-sidekiq'
gem 'sidekiq', '~> 4.1.2'
gem 'sidetiq'

gem 'carrierwave', '~> 0.11'
gem 'carrierwave-qiniu', '0.2.0' # 暂勿升级

# pdf
gem 'prawn'
gem 'combine_pdf'
gem 'pdf-reader'

## notice channel
gem 'jpush', '~> 4.0.2'
gem 'private_pub' # faye
gem 'cloopen', :git => 'git://github.com/xiewenwei/cloopen.git' # sms
gem 'wechat'
