client:
  build: client
  dockerfile: Dockerfile
  links:
    - server
    - logstash

server:
  build: server
  dockerfile: Dockerfile

logstash:
  image: logstash
  ports: 
    - "1514:1514"
  privileged: true
  command: logstash -e 'input { syslog { port => 1514 } } output { stdout { codec => rubydebug } }' 
