# -*- coding: utf-8 -*-
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'parser', '2.3.1.0'
gem 'pg'
gem 'postgres_ext', '~> 3.0.0'
gem 'ruby-pinyin', '~> 0.5.0'
gem 'bcrypt', '~> 3.1.11'

gem 'doorkeeper', '~> 3.1.0'
gem 'kaminari', '~> 0.16.3'
gem 'mini_magick', '~> 4.5.1'

gem 'autoprefixer-rails', '~> 6.3.6.1'


gem 'puma', '~> 3.4.0'
gem 'rack-attack', '~> 4.4.1' # api limit
gem 'rack-cors', '~> 0.4.0'
gem 'jbuilder', '~> 2.4.1'
gem 'has_scope', '~> 0.7.0'

gem 'cancancan', '~> 1.14.0'
gem 'wisper', '~> 2.0.0.rc1'
gem 'wisper-sidekiq'
gem 'aasm', '~> 4.10'
gem 'paranoia', '~> 2.1.5' # 软删除
gem 'active_link_to'

gem 'acts_as_list'
gem 'carrierwave', '~> 0.11'
gem 'carrierwave-qiniu', '0.2.0' # 暂勿升级
gem 'letter_avatar'
gem 'oneapm_rpm', '~> 1.3.6'
gem 'httparty', '~> 0.13.7'

gem 'redis', '~> 3.3.0'
gem 'redis-rails', '~> 4.0.0'
gem 'sidekiq', '~> 4.1.2'
gem 'sidetiq'
gem 'redis-namespace' # removed from sidekiq dependence, we still need it
gem 'sinatra', require: nil
gem 'json-schema', '~> 2.6.2'
gem 'jpush', '~> 4.0.2'
gem 'paper_trail', '~> 4.1.0'
gem 'oauth2', require: false # OAuth api test tools

gem 'client_side_validations'
gem 'ransack', '~> 1.7.0'

gem 'sprockets-rails', '3.0.4'
gem 'sassc-rails'
gem 'uglifier', '3.0.0'
gem 'turbolinks'
gem 'bower-rails', '~> 0.10.0'
gem 'multi_fetch_fragments'
gem 'lograge', :git => "git://github.com/zhulux/lograge.git"
gem 'logstash-event'

gem 'unscoped_associations' # support unscoped for association

#gem "react_on_rails"

group :development, :test, :staging do
  gem 'factory_girl_rails', '~> 4.7.0'
  gem 'ffaker'
end


group :development, :staging do
  gem 'web-console', '3.1.1'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'bullet' # n+1 query limit
  gem 'overcommit', require: false # git before commit hook
  gem 'brakeman', '~> 3.1.5', require: false # Rails static analysis security scanner
  gem 'rubocop', require: false # Code Style scanner
  gem 'byebug'

  #gem 'spring'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'pry-doc'

  gem 'quiet_assets'
  #gem 'annotate', '~> 2.7.1'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'meta_request'
  gem 'binding_of_caller'
  gem 'letter_opener'

  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-livereload', '~> 2.5', require: false
end

group :test do
  gem 'rspec-activejob'
  gem 'test_after_commit'
  gem 'database_cleaner'
end

# pdf
gem 'prawn'
gem 'combine_pdf'
gem 'pdf-reader'

# SMS service
gem 'cloopen', '~> 0.1.4'

# rpc invocation
gem 'thrift'

# UI component
gem 'cells-rails'
gem 'cells-erb'
gem 'kaminari-cells'

# http pub/sub
gem 'private_pub'

gem 'wechat'
gem 'rqrcode'

gem 'simple_calendar', '~> 2.0'

